default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kevin

development:
  <<: *default
  database: smartvent_development

test:
  <<: *default
  database: smartvent_test
